import { Head, router, useForm, usePage } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import { FiActivity, FiCalendar, FiCheckCircle, FiClock, FiPlay, FiTool, FiUser, FiX } from 'react-icons/fi';
import Layout from '@/Pages/Admin/Recruitment/Layout';
import VelvetDateTimeField from '@/Components/VelvetDateTimeField';
import { subscribeToRealtime } from '@/lib/ably';

function PortalLayout({ children, eyebrow, title, subtitle }) {
    const roomsPage = window.location.pathname === '/monitor/rooms';
    const { operationalAccess } = usePage().props;
    return <Layout><div className="admin-page-content"><div className="flex flex-col justify-between gap-5 border-b border-[#20232d] pb-7 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[.28em] text-[#d56bea]">{roomsPage ? 'Operación · Rooms' : eyebrow}</p><h1 className="mt-2 font-editorial text-4xl text-white">{roomsPage ? 'Rooms' : title}</h1><p className="mt-2 text-sm text-[#969baa]">{roomsPage ? 'Consulta estados, programa reservas y administra el uso según tus permisos.' : subtitle}</p></div><span className="rounded-lg border border-[#343044] px-3 py-2 text-xs text-[#aaa5b5]">{roomsPage ? 'Módulo operativo' : 'Vista operativa'}</span></div>{operationalAccess && !operationalAccess.is_active && <div className="mt-7 rounded-xl border border-[#b8863b] bg-[#342515]/60 p-4 sm:p-5"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#ffe1a1]">Modo inducción</p><p className="mt-2 text-sm text-white">Tu perfil está en preparación operativa.</p><p className="mt-1 text-xs leading-5 text-[#dfc99e]">Puedes consultar el módulo, pero las acciones sobre datos reales se habilitarán cuando administración active tu perfil.</p></div>}{children}</div></Layout>;
}

const labels = { AVAILABLE: 'Disponible', RESERVED: 'Reservada', IN_USE: 'En uso', MAINTENANCE: 'Mantenimiento', BLOCKED: 'Bloqueada', SCHEDULED: 'Programada', COMPLETED: 'Finalizada', CANCELLED: 'Cancelada', NO_SHOW: 'No se presentó' };
const styles = { AVAILABLE: 'border-[#2d8669] bg-[#12372e] text-[#9af2cb]', RESERVED: 'border-[#80508c] bg-[#321344] text-[#e5a5f2]', IN_USE: 'border-[#b66a2c] bg-[#422718] text-[#ffc58e]', MAINTENANCE: 'border-[#755d2a] bg-[#3b3017] text-[#f5d88c]', BLOCKED: 'border-[#7d3144] bg-[#321622] text-[#ffb1bd]' };
const date = (value) => value ? new Intl.DateTimeFormat('es-CO', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Bogota' }).format(new Date(value)) : 'Sin horario';
function Badge({ value }) { return <span className={`rounded-full border px-2.5 py-1 text-[11px] ${styles[value] || 'border-[#343044] bg-[#171522] text-[#bdb7c7]'}`}>{labels[value] || value}</span>; }

export default function Dashboard({ rooms = [], reservations = [], candidates = [], canReserve = false, canUse = false, trainingMode = false }) {
    const [room, setRoom] = useState(null);
    const form = useForm({ room_id: '', candidate_id: '', purpose: 'Sesión de estudio', starts_at: '', ends_at: '', notes: '' });
    const reload = () => router.reload({ only: ['rooms', 'reservations'], preserveScroll: true });
    useEffect(() => subscribeToRealtime((_data, event) => event?.startsWith('room.') && reload()), []);
    const operationalPath = '/monitor/rooms/reservations';
    const trainingQuery = trainingMode ? '?sandbox=1' : '';
    const save = (event) => { event.preventDefault(); form.post(`${operationalPath}${trainingQuery}`, { preserveScroll: true, onSuccess: () => { setRoom(null); form.reset(); } }); };
    const changeStatus = (reservation, status) => router.patch(`${operationalPath}/${reservation.id}/status${trainingQuery}`, { status }, { preserveScroll: true });
    const stats = { available: rooms.filter((item) => item.effective_status === 'AVAILABLE').length, reserved: rooms.filter((item) => item.effective_status === 'RESERVED').length, inUse: rooms.filter((item) => item.effective_status === 'IN_USE').length, maintenance: rooms.filter((item) => ['MAINTENANCE', 'BLOCKED'].includes(item.effective_status)).length };

    return <><Head title="Portal de monitor" /><PortalLayout eyebrow="Operación de rooms" title="Panel del monitor" subtitle="Administra las reservas y registra el uso de las rooms en tiempo real. La creación y edición de rooms pertenece al administrador.">
        <section className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<FiCheckCircle />} value={stats.available} label="Disponibles" /><Stat icon={<FiCalendar />} value={stats.reserved} label="Reservadas" /><Stat icon={<FiActivity />} value={stats.inUse} label="En uso ahora" /><Stat icon={<FiTool />} value={stats.maintenance} label="Mantenimiento / bloqueadas" /></section>
        <div className="mt-7 flex items-center gap-2 text-xs text-[#65e6ad]"><span className="h-2 w-2 rounded-full bg-[#65e6ad] shadow-[0_0_10px_#65e6ad]" />Estados sincronizados en tiempo real</div>
        <section className="mt-4 grid gap-5 lg:grid-cols-2">{rooms.map((item) => <article key={item.id} className="rounded-xl border border-[#292d39] bg-[#11131c]/90 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#d56bea]">{item.code}</p><h2 className="mt-1 text-lg text-white">{item.name}</h2></div><Badge value={item.effective_status} /></div><p className="mt-3 text-xs text-[#858a99]">{item.description || 'Room sin descripción.'}</p>{item.current ? <div className="mt-4 rounded-lg border border-[#6e4326] bg-[#241a16] p-3"><p className="flex items-center gap-2 text-sm text-[#f2e5db]"><FiUser />{item.current.candidate_name || 'Responsable interno'}</p><p className="mt-1 text-xs text-[#b89c88]">{item.current.purpose} · termina {date(item.current.ends_at)}</p><div className="mt-3 flex gap-2">{canUse && item.current.status === 'SCHEDULED' && <button type="button" onClick={() => changeStatus(item.current, 'IN_USE')} className="inline-flex items-center gap-1 rounded-md border border-[#9e5d28] px-2.5 py-1.5 text-[11px] text-[#ffc58e]"><FiPlay />Iniciar</button>}{canUse && item.current.status === 'IN_USE' && <button type="button" onClick={() => changeStatus(item.current, 'COMPLETED')} className="inline-flex items-center gap-1 rounded-md border border-[#5c8f78] px-2.5 py-1.5 text-[11px] text-[#a7e9c8]"><FiCheckCircle />Finalizar</button>}</div></div> : <div className="mt-4 rounded-lg border border-dashed border-[#343044] p-4 text-center text-xs text-[#777d8f]">Sin uso en este momento</div>}{item.upcoming && <p className="mt-3 text-xs text-[#858a99]"><FiClock className="mr-1 inline" />Próxima reserva: {item.upcoming.candidate_name || 'Sin modelo'} · {date(item.upcoming.starts_at)}</p>}{canReserve && item.status === 'AVAILABLE' && <button type="button" onClick={() => { form.reset(); form.setData({ room_id: item.id, candidate_id: '', purpose: 'Sesión de estudio', starts_at: '', ends_at: '', notes: '' }); setRoom(item); }} className="velvet-button mt-5 w-full gap-2"><FiCalendar />Programar reserva</button>}</article>)}</section>
        <section className="mt-8 rounded-xl border border-[#292d39] bg-[#11131c]/90 p-5"><div className="flex items-center gap-3"><FiCalendar className="text-[#d56bea]" /><div><h2 className="text-sm font-medium text-white">Reservas activas y próximas</h2><p className="mt-1 text-xs text-[#7f8495]">El monitor puede programar, iniciar, finalizar o cancelar reservas; no puede crear rooms.</p></div></div><div className="mt-5 space-y-3">{reservations.length ? reservations.map((item) => <div key={item.id} className="flex flex-col justify-between gap-3 rounded-lg border border-[#292d39] bg-[#151522] p-4 sm:flex-row sm:items-center"><div><p className="text-sm text-white">{item.candidate_name || 'Responsable interno'} <span className="text-[#7f8495]">· {item.room_name}</span></p><p className="mt-1 text-xs text-[#858a99]">{date(item.starts_at)} — {date(item.ends_at)} · {item.purpose}</p></div><div className="flex items-center gap-2"><Badge value={item.status} />{canUse && item.status === 'SCHEDULED' && <button type="button" onClick={() => changeStatus(item, 'IN_USE')} className="inline-flex items-center gap-1 rounded-md border border-[#9e5d28] px-2.5 py-1.5 text-[11px] text-[#ffc58e]"><FiPlay />Iniciar</button>}{canUse && item.status === 'IN_USE' && <button type="button" onClick={() => changeStatus(item, 'COMPLETED')} className="inline-flex items-center gap-1 rounded-md border border-[#5c8f78] px-2.5 py-1.5 text-[11px] text-[#a7e9c8]"><FiCheckCircle />Finalizar</button>}{canUse && item.status === 'SCHEDULED' && <button type="button" onClick={() => changeStatus(item, 'CANCELLED')} className="inline-flex items-center gap-1 rounded-md border border-[#7d3144] px-2.5 py-1.5 text-[11px] text-[#ffb1bd]"><FiX />Cancelar</button>}</div></div>) : <p className="py-8 text-center text-sm text-[#777d8f]">No hay reservas activas o próximas.</p>}</div></section>
    </PortalLayout>{room && <div className="fixed inset-0 z-[80] grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><section className="w-full max-w-lg rounded-2xl border border-[#4c3157] bg-[#11121a] p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-[#d56bea]">Programar uso</p><h2 className="mt-2 font-editorial text-3xl text-white">{room.name}</h2></div><button type="button" onClick={() => setRoom(null)} className="text-[#858a99]"><FiX /></button></div><form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs text-[#c8c2ce] sm:col-span-2">Modelo<select value={form.data.candidate_id} onChange={(event) => form.setData('candidate_id', event.target.value)} className="velvet-input" required><option value="">Selecciona una modelo</option>{candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name} · {candidate.code}</option>)}</select>{form.errors.candidate_id && <span className="text-[#ffb1bd]">{form.errors.candidate_id}</span>}</label><label className="text-xs text-[#c8c2ce] sm:col-span-2">Propósito<input value={form.data.purpose} onChange={(event) => form.setData('purpose', event.target.value)} className="velvet-input" required /></label><VelvetDateTimeField label="Inicio" value={form.data.starts_at} onChange={(event) => form.setData('starts_at', event.target.value)} error={form.errors.starts_at} /><VelvetDateTimeField label="Fin" value={form.data.ends_at} onChange={(event) => form.setData('ends_at', event.target.value)} error={form.errors.ends_at} /><label className="text-xs text-[#c8c2ce] sm:col-span-2">Notas<textarea value={form.data.notes} onChange={(event) => form.setData('notes', event.target.value)} className="velvet-input" rows="3" /></label><div className="flex justify-end gap-3 border-t border-[#292d39] pt-4 sm:col-span-2"><button type="button" onClick={() => setRoom(null)} className="rounded-lg border border-[#343044] px-4 py-2 text-xs">Cancelar</button><button type="submit" disabled={form.processing} className="velvet-button">{form.processing ? 'Guardando…' : 'Programar reserva'}</button></div></form></section></div>}</>;
}

function Stat({ icon, value, label }) { return <div className="rounded-xl border border-[#292d39] bg-[#11131c]/90 p-5"><span className="text-[#d56bea]">{icon}</span><p className="mt-4 text-2xl text-white">{value}</p><p className="mt-1 text-xs text-[#858a99]">{label}</p></div>; }
