import { Head, Link, useForm } from '@inertiajs/react';
import { FiArrowLeft, FiCheck } from 'react-icons/fi';
import Layout from '../Recruitment/Layout';

export default function UserForm({ user, roles }) {
    const form = useForm({ roles: user.roles.map((role) => role.slug) });
    const toggle = (slug) => form.setData('roles', form.data.roles.includes(slug) ? form.data.roles.filter((role) => role !== slug) : [...form.data.roles, slug]);
    const submit = (event) => { event.preventDefault(); form.put(`/admin/users/${user.id}`); };

    return <><Head title={`Acceso · ${user.name}`} /><Layout><div className="mx-auto max-w-[760px]"><Link href="/admin/users" className="inline-flex items-center gap-2 text-sm text-[#d56bea] hover:text-white"><FiArrowLeft size={15} /> Usuarios y accesos</Link><div className="mt-7"><p className="text-[10px] uppercase tracking-[.28em] text-[#d56bea]">Asignación de acceso</p><h1 className="mt-2 font-editorial text-4xl text-white">{user.name}</h1><p className="mt-2 text-sm text-[#969baa]">{user.email}</p></div><form onSubmit={submit} className="mt-8 rounded-xl border border-[#292d39] bg-[#11131c]/90 p-6 sm:p-8"><p className="text-sm text-white">Selecciona los roles del usuario</p><div className="mt-6 space-y-3">{roles.map((role) => { const checked = form.data.roles.includes(role.slug); return <label key={role.id} className={`flex cursor-pointer items-center justify-between rounded-lg border p-4 transition ${checked ? 'border-[#9f35b9] bg-[#32163e]' : 'border-[#292d39] bg-[#151722] hover:border-[#5b3267]'}`}><span><span className="block text-sm text-white">{role.name}</span><span className="mt-1 block text-xs text-[#858a99]">{role.description}</span></span><span className={`grid h-5 w-5 place-items-center rounded border ${checked ? 'border-[#c23bea] bg-[#c23bea] text-white' : 'border-[#5c6070] text-transparent'}`}><input type="checkbox" className="sr-only" checked={checked} onChange={() => toggle(role.slug)} /><FiCheck size={13} /></span></label>; })}</div><div className="mt-8 flex justify-between gap-4"><Link href="/admin/users" className="rounded-lg border border-[#353846] px-5 py-3 text-sm text-[#c7c4cf] hover:bg-white/5">Cancelar</Link><button type="submit" disabled={form.processing} className="velvet-button">{form.processing ? 'Guardando…' : 'Guardar acceso →'}</button></div></form></div></Layout></>;
}
