// Catálogo local de municipios de Colombia (DANE/MinTIC).
export const colombianCities = [...new Set([
    'Medellín',
    'Abejorral',
    'Abriaquí',
    'Alejandría',
    'Amagá',
    'Amalfi',
    'Andes',
    'Angelópolis',
    'Angostura',
    'Anorí',
    'Santafé de Antioquia',
    'Anza',
    'Apartadó',
    'Arboletes',
    'Argelia',
    'Armenia',
    'Barbosa',
    'Belmira',
    'Bello',
    'Betania',
    'Betulia',
    'Ciudad Bolívar',
    'Briceño',
    'Buriticá',
    'Cáceres',
    'Caicedo',
    'Caldas',
    'Campamento',
    'Cañasgordas',
    'Caracolí',
    'Caramanta',
    'Carepa',
    'El Carmen de Viboral',
    'Carolina',
    'Caucasia',
    'Chigorodó',
    'Cisneros',
    'Cocorná',
    'Concepción',
    'Concordia',
    'Copacabana',
    'Dabeiba',
    'Don Matías',
    'Ebéjico',
    'El Bagre',
    'Entrerrios',
    'Envigado',
    'Fredonia',
    'Frontino',
    'Giraldo',
    'Girardota',
    'Gómez Plata',
    'Granada',
    'Guadalupe',
    'Guarne',
    'Guatapé',
    'Heliconia',
    'Hispania',
    'Itagui',
    'Ituango',
    'Jardín',
    'Jericó',
    'La Ceja',
    'La Estrella',
    'La Pintada',
    'La Unión',
    'Liborina',
    'Maceo',
    'Marinilla',
    'Montebello',
    'Murindó',
    'Mutatá',
    'Nariño',
    'Necoclí',
    'Nechí',
    'Olaya',
    'Peñol',
    'Peque',
    'Pueblorrico',
    'Puerto Berrío',
    'Puerto Nare',
    'Puerto Triunfo',
    'Remedios',
    'Retiro',
    'Rionegro',
    'Sabanalarga',
    'Sabaneta',
    'Salgar',
    'San Andrés de Cuerquía',
    'San Carlos',
    'San Francisco',
    'San Jerónimo',
    'San José de La Montaña',
    'San Juan de Urabá',
    'San Luis',
    'San Pedro',
    'San Pedro de Uraba',
    'San Rafael',
    'San Roque',
    'San Vicente',
    'Santa Bárbara',
    'Santa Rosa de Osos',
    'Santo Domingo',
    'El Santuario',
    'Segovia',
    'Sonsón',
    'Sopetrán',
    'Támesis',
    'Tarazá',
    'Tarso',
    'Titiribí',
    'Toledo',
    'Turbo',
    'Uramita',
    'Urrao',
    'Valdivia',
    'Valparaíso',
    'Vegachí',
    'Venecia',
    'Vigía del Fuerte',
    'Yalí',
    'Yarumal',
    'Yolombó',
    'Yondó',
    'Zaragoza',
    'Barranquilla',
    'Baranoa',
    'Campo de La Cruz',
    'Candelaria',
    'Galapa',
    'Juan de Acosta',
    'Luruaco',
    'Malambo',
    'Manatí',
    'Palmar de Varela',
    'Piojó',
    'Polonuevo',
    'Ponedera',
    'Puerto Colombia',
    'Repelón',
    'Sabanagrande',
    'Sabanalarga',
    'Santa Lucía',
    'Santo Tomás',
    'Soledad',
    'Suan',
    'Tubará',
    'Usiacurí',
    'Bogotá D.C.',
    'Cartagena',
    'Achí',
    'Altos del Rosario',
    'Arenal',
    'Arjona',
    'Arroyohondo',
    'Barranco de Loba',
    'Calamar',
    'Cantagallo',
    'Cicuco',
    'Córdoba',
    'Clemencia',
    'El Carmen de Bolívar',
    'El Guamo',
    'El Peñón',
    'Hatillo de Loba',
    'Magangué',
    'Mahates',
    'Margarita',
    'María la Baja',
    'Montecristo',
    'Mompós',
    'Morales',
    'Norosí',
    'Pinillos',
    'Regidor',
    'Río Viejo',
    'San Cristóbal',
    'San Estanislao',
    'San Fernando',
    'San Jacinto',
    'San Jacinto del Cauca',
    'San Juan Nepomuceno',
    'San Martín de Loba',
    'San Pablo de Borbur',
    'Santa Catalina',
    'Santa Rosa',
    'Santa Rosa del Sur',
    'Simití',
    'Soplaviento',
    'Talaigua Nuevo',
    'Tiquisio',
    'Turbaco',
    'Turbaná',
    'Villanueva',
    'Zambrano',
    'Tunja',
    'Almeida',
    'Aquitania',
    'Arcabuco',
    'Belén',
    'Berbeo',
    'Betéitiva',
    'Boavita',
    'Boyacá',
    'Briceño',
    'Buena Vista',
    'Busbanzá',
    'Caldas',
    'Campohermoso',
    'Cerinza',
    'Chinavita',
    'Chiquinquirá',
    'Chiscas',
    'Chita',
    'Chitaraque',
    'Chivatá',
    'Ciénega',
    'Cómbita',
    'Coper',
    'Corrales',
    'Covarachía',
    'Cubará',
    'Cucaita',
    'Cuítiva',
    'Chíquiza',
    'Chivor',
    'Duitama',
    'El Cocuy',
    'El Espino',
    'Firavitoba',
    'Floresta',
    'Gachantivá',
    'Gameza',
    'Garagoa',
    'Guacamayas',
    'Guateque',
    'Guayatá',
    'Güicán',
    'Iza',
    'Jenesano',
    'Jericó',
    'Labranzagrande',
    'La Capilla',
    'La Victoria',
    'La Uvita',
    'Villa de Leyva',
    'Macanal',
    'Maripí',
    'Miraflores',
    'Mongua',
    'Monguí',
    'Moniquirá',
    'Motavita',
    'Muzo',
    'Nobsa',
    'Nuevo Colón',
    'Oicatá',
    'Otanche',
    'Pachavita',
    'Páez',
    'Paipa',
    'Pajarito',
    'Panqueba',
    'Pauna',
    'Paya',
    'Paz de Río',
    'Pesca',
    'Pisba',
    'Puerto Boyacá',
    'Quípama',
    'Ramiriquí',
    'Ráquira',
    'Rondón',
    'Saboyá',
    'Sáchica',
    'Samacá',
    'San Eduardo',
    'San José de Pare',
    'San Luis de Gaceno',
    'San Mateo',
    'San Miguel de Sema',
    'San Pablo de Borbur',
    'Santana',
    'Santa María',
    'Santa Rosa de Viterbo',
    'Santa Sofía',
    'Sativanorte',
    'Sativasur',
    'Siachoque',
    'Soatá',
    'Socotá',
    'Socha',
    'Sogamoso',
    'Somondoco',
    'Sora',
    'Sotaquirá',
    'Soracá',
    'Susacón',
    'Sutamarchán',
    'Sutatenza',
    'Tasco',
    'Tenza',
    'Tibaná',
    'Tibasosa',
    'Tinjacá',
    'Tipacoque',
    'Toca',
    'Togüí',
    'Tópaga',
    'Tota',
    'Tununguá',
    'Turmequé',
    'Tuta',
    'Tutazá',
    'Umbita',
    'Ventaquemada',
    'Viracachá',
    'Zetaquira',
    'Manizales',
    'Aguadas',
    'Anserma',
    'Aranzazu',
    'Belalcázar',
    'Chinchiná',
    'Filadelfia',
    'La Dorada',
    'La Merced',
    'Manzanares',
    'Marmato',
    'Marquetalia',
    'Marulanda',
    'Neira',
    'Norcasia',
    'Pácora',
    'Palestina',
    'Pensilvania',
    'Riosucio',
    'Risaralda',
    'Salamina',
    'Samaná',
    'San José',
    'Supía',
    'Victoria',
    'Villamaría',
    'Viterbo',
    'Florencia',
    'Albania',
    'Belén de Los Andaquies',
    'Cartagena del Chairá',
    'Curillo',
    'El Doncello',
    'El Paujil',
    'La Montañita',
    'Milán',
    'Morelia',
    'Puerto Rico',
    'San José del Fragua',
    'San Vicente del Caguán',
    'Solano',
    'Solita',
    'Valparaíso',
    'Popayán',
    'Almaguer',
    'Argelia',
    'Balboa',
    'Bolívar',
    'Buenos Aires',
    'Cajibío',
    'Caldono',
    'Caloto',
    'Corinto',
    'El Tambo',
    'Florencia',
    'Guachené',
    'Guapi',
    'Inzá',
    'Jambaló',
    'La Sierra',
    'La Vega',
    'López',
    'Mercaderes',
    'Miranda',
    'Morales',
    'Padilla',
    'Páez',
    'Patía',
    'Piamonte',
    'Piendamó',
    'Puerto Tejada',
    'Puracé',
    'Rosas',
    'San Sebastián',
    'Santander de Quilichao',
    'Santa Rosa',
    'Silvia',
    'Sotara',
    'Suárez',
    'Sucre',
    'Timbío',
    'Timbiquí',
    'Toribio',
    'Totoró',
    'Villa Rica',
    'Valledupar',
    'Aguachica',
    'Agustín Codazzi',
    'Astrea',
    'Becerril',
    'Bosconia',
    'Chimichagua',
    'Chiriguaná',
    'Curumaní',
    'El Copey',
    'El Paso',
    'Gamarra',
    'González',
    'La Gloria',
    'La Jagua de Ibirico',
    'Manaure',
    'Pailitas',
    'Pelaya',
    'Pueblo Bello',
    'Río de Oro',
    'La Paz',
    'San Alberto',
    'San Diego',
    'San Martín',
    'Tamalameque',
    'Montería',
    'Ayapel',
    'Buenavista',
    'Canalete',
    'Cereté',
    'Chimá',
    'Chinú',
    'Ciénaga de Oro',
    'Cotorra',
    'La Apartada',
    'Lorica',
    'Los Córdobas',
    'Momil',
    'Montelíbano',
    'Moñitos',
    'Planeta Rica',
    'Pueblo Nuevo',
    'Puerto Escondido',
    'Puerto Libertador',
    'Purísima',
    'Sahagún',
    'San Andrés Sotavento',
    'San Antero',
    'San Bernardo del Viento',
    'San Carlos',
    'San José de Uré',
    'San Pelayo',
    'Tierralta',
    'Tuchín',
    'Valencia',
    'Agua de Dios',
    'Albán',
    'Anapoima',
    'Anolaima',
    'Arbeláez',
    'Beltrán',
    'Bituima',
    'Bojacá',
    'Cabrera',
    'Cachipay',
    'Cajicá',
    'Caparrapí',
    'Caqueza',
    'Carmen de Carupa',
    'Chaguaní',
    'Chía',
    'Chipaque',
    'Choachí',
    'Chocontá',
    'Cogua',
    'Cota',
    'Cucunubá',
    'El Colegio',
    'El Peñón',
    'El Rosal',
    'Facatativá',
    'Fomeque',
    'Fosca',
    'Funza',
    'Fúquene',
    'Fusagasugá',
    'Gachala',
    'Gachancipá',
    'Gachetá',
    'Gama',
    'Girardot',
    'Granada',
    'Guachetá',
    'Guaduas',
    'Guasca',
    'Guataquí',
    'Guatavita',
    'Guayabal de Siquima',
    'Guayabetal',
    'Gutiérrez',
    'Jerusalén',
    'Junín',
    'La Calera',
    'La Mesa',
    'La Palma',
    'La Peña',
    'La Vega',
    'Lenguazaque',
    'Macheta',
    'Madrid',
    'Manta',
    'Medina',
    'Mosquera',
    'Nariño',
    'Nemocón',
    'Nilo',
    'Nimaima',
    'Nocaima',
    'Venecia',
    'Pacho',
    'Paime',
    'Pandi',
    'Paratebueno',
    'Pasca',
    'Puerto Salgar',
    'Pulí',
    'Quebradanegra',
    'Quetame',
    'Quipile',
    'Apulo',
    'Ricaurte',
    'San Antonio del Tequendama',
    'San Bernardo',
    'San Cayetano',
    'San Francisco',
    'San Juan de Río Seco',
    'Sasaima',
    'Sesquilé',
    'Sibaté',
    'Silvania',
    'Simijaca',
    'Soacha',
    'Sopó',
    'Subachoque',
    'Suesca',
    'Supatá',
    'Susa',
    'Sutatausa',
    'Tabio',
    'Tausa',
    'Tena',
    'Tenjo',
    'Tibacuy',
    'Tibirita',
    'Tocaima',
    'Tocancipá',
    'Topaipí',
    'Ubalá',
    'Ubaque',
    'Villa de San Diego de Ubate',
    'Une',
    'Útica',
    'Vergara',
    'Vianí',
    'Villagómez',
    'Villapinzón',
    'Villeta',
    'Viotá',
    'Yacopí',
    'Zipacón',
    'Zipaquirá',
    'Quibdó',
    'Acandí',
    'Alto Baudo',
    'Atrato',
    'Bagadó',
    'Bahía Solano',
    'Bajo Baudó',
    'Belén de Bajira',
    'Bojaya',
    'El Cantón del San Pablo',
    'Carmen del Darien',
    'Cértegui',
    'Condoto',
    'El Carmen de Atrato',
    'El Litoral del San Juan',
    'Istmina',
    'Juradó',
    'Lloró',
    'Medio Atrato',
    'Medio Baudó',
    'Medio San Juan',
    'Nóvita',
    'Nuquí',
    'Río Iro',
    'Río Quito',
    'Riosucio',
    'San José del Palmar',
    'Sipí',
    'Tadó',
    'Unguía',
    'Unión Panamericana',
    'Neiva',
    'Acevedo',
    'Agrado',
    'Aipe',
    'Algeciras',
    'Altamira',
    'Baraya',
    'Campoalegre',
    'Colombia',
    'Elías',
    'Garzón',
    'Gigante',
    'Guadalupe',
    'Hobo',
    'Iquira',
    'Isnos',
    'La Argentina',
    'La Plata',
    'Nátaga',
    'Oporapa',
    'Paicol',
    'Palermo',
    'Palestina',
    'Pital',
    'Pitalito',
    'Rivera',
    'Saladoblanco',
    'San Agustín',
    'Santa María',
    'Suaza',
    'Tarqui',
    'Tesalia',
    'Tello',
    'Teruel',
    'Timaná',
    'Villavieja',
    'Yaguará',
    'Riohacha',
    'Albania',
    'Barrancas',
    'Dibula',
    'Distracción',
    'El Molino',
    'Fonseca',
    'Hatonuevo',
    'La Jagua del Pilar',
    'Maicao',
    'Manaure',
    'San Juan del Cesar',
    'Uribia',
    'Urumita',
    'Villanueva',
    'Santa Marta',
    'Algarrobo',
    'Aracataca',
    'Ariguaní',
    'Cerro San Antonio',
    'Chivolo',
    'Ciénaga',
    'Concordia',
    'El Banco',
    'El Piñon',
    'El Retén',
    'Fundación',
    'Guamal',
    'Nueva Granada',
    'Pedraza',
    'Pijiño del Carmen',
    'Pivijay',
    'Plato',
    'Pueblo Viejo',
    'Remolino',
    'Sabanas de San Angel',
    'Salamina',
    'San Sebastián de Buenavista',
    'San Zenón',
    'Santa Ana',
    'Santa Bárbara de Pinto',
    'Sitionuevo',
    'Tenerife',
    'Zapayán',
    'Zona Bananera',
    'Villavicencio',
    'Acacias',
    'Barranca de Upía',
    'Cabuyaro',
    'Castilla la Nueva',
    'Cubarral',
    'Cumaral',
    'El Calvario',
    'El Castillo',
    'El Dorado',
    'Fuente de Oro',
    'Granada',
    'Guamal',
    'Mapiripán',
    'Mesetas',
    'La Macarena',
    'Uribe',
    'Lejanías',
    'Puerto Concordia',
    'Puerto Gaitán',
    'Puerto López',
    'Puerto Lleras',
    'Puerto Rico',
    'Restrepo',
    'San Carlos de Guaroa',
    'San Juan de Arama',
    'San Juanito',
    'San Martín',
    'Vista Hermosa',
    'Pasto',
    'Albán',
    'Aldana',
    'Ancuyá',
    'Arboleda',
    'Barbacoas',
    'Belén',
    'Buesaco',
    'Colón',
    'Consaca',
    'Contadero',
    'Córdoba',
    'Cuaspud',
    'Cumbal',
    'Cumbitara',
    'Chachagüí',
    'El Charco',
    'El Peñol',
    'El Rosario',
    'El Tablón de Gómez',
    'El Tambo',
    'Funes',
    'Guachucal',
    'Guaitarilla',
    'Gualmatán',
    'Iles',
    'Imués',
    'Ipiales',
    'La Cruz',
    'La Florida',
    'La Llanada',
    'La Tola',
    'La Unión',
    'Leiva',
    'Linares',
    'Los Andes',
    'Magüí',
    'Mallama',
    'Mosquera',
    'Nariño',
    'Olaya Herrera',
    'Ospina',
    'Francisco Pizarro',
    'Policarpa',
    'Potosí',
    'Providencia',
    'Puerres',
    'Pupiales',
    'Ricaurte',
    'Roberto Payán',
    'Samaniego',
    'Sandoná',
    'San Bernardo',
    'San Lorenzo',
    'San Pablo',
    'San Pedro de Cartago',
    'Santa Bárbara',
    'Santacruz',
    'Sapuyes',
    'Taminango',
    'Tangua',
    'San Andrés de Tumaco',
    'Túquerres',
    'Yacuanquer',
    'Cúcuta',
    'Abrego',
    'Arboledas',
    'Bochalema',
    'Bucarasica',
    'Cácota',
    'Cachirá',
    'Chinácota',
    'Chitagá',
    'Convención',
    'Cucutilla',
    'Durania',
    'El Carmen',
    'El Tarra',
    'El Zulia',
    'Gramalote',
    'Hacarí',
    'Herrán',
    'Labateca',
    'La Esperanza',
    'La Playa',
    'Los Patios',
    'Lourdes',
    'Mutiscua',
    'Ocaña',
    'Pamplona',
    'Pamplonita',
    'Puerto Santander',
    'Ragonvalia',
    'Salazar',
    'San Calixto',
    'San Cayetano',
    'Santiago',
    'Sardinata',
    'Silos',
    'Teorama',
    'Tibú',
    'Toledo',
    'Villa Caro',
    'Villa del Rosario',
    'Armenia',
    'Buenavista',
    'Calarcá',
    'Circasia',
    'Córdoba',
    'Filandia',
    'Génova',
    'La Tebaida',
    'Montenegro',
    'Pijao',
    'Quimbaya',
    'Salento',
    'Pereira',
    'Apía',
    'Balboa',
    'Belén de Umbría',
    'Dosquebradas',
    'Guática',
    'La Celia',
    'La Virginia',
    'Marsella',
    'Mistrató',
    'Pueblo Rico',
    'Quinchía',
    'Santa Rosa de Cabal',
    'Santuario',
    'Bucaramanga',
    'Aguada',
    'Albania',
    'Aratoca',
    'Barbosa',
    'Barichara',
    'Barrancabermeja',
    'Betulia',
    'Bolívar',
    'Cabrera',
    'California',
    'Capitanejo',
    'Carcasí',
    'Cepitá',
    'Cerrito',
    'Charalá',
    'Charta',
    'Chimá',
    'Chipatá',
    'Cimitarra',
    'Concepción',
    'Confines',
    'Contratación',
    'Coromoro',
    'Curití',
    'El Carmen de Chucurí',
    'El Guacamayo',
    'El Peñón',
    'El Playón',
    'Encino',
    'Enciso',
    'Florián',
    'Floridablanca',
    'Galán',
    'Gambita',
    'Girón',
    'Guaca',
    'Guadalupe',
    'Guapotá',
    'Guavatá',
    'Güepsa',
    'Hato',
    'Jesús María',
    'Jordán',
    'La Belleza',
    'Landázuri',
    'La Paz',
    'Lebríja',
    'Los Santos',
    'Macaravita',
    'Málaga',
    'Matanza',
    'Mogotes',
    'Molagavita',
    'Ocamonte',
    'Oiba',
    'Onzaga',
    'Palmar',
    'Palmas del Socorro',
    'Páramo',
    'Piedecuesta',
    'Pinchote',
    'Puente Nacional',
    'Puerto Parra',
    'Puerto Wilches',
    'Rionegro',
    'Sabana de Torres',
    'San Andrés',
    'San Benito',
    'San Gil',
    'San Joaquín',
    'San José de Miranda',
    'San Miguel',
    'San Vicente de Chucurí',
    'Santa Bárbara',
    'Santa Helena del Opón',
    'Simacota',
    'Socorro',
    'Suaita',
    'Sucre',
    'Suratá',
    'Tona',
    'Valle de San José',
    'Vélez',
    'Vetas',
    'Villanueva',
    'Zapatoca',
    'Sincelejo',
    'Buenavista',
    'Caimito',
    'Coloso',
    'Corozal',
    'Coveñas',
    'Chalán',
    'El Roble',
    'Galeras',
    'Guaranda',
    'La Unión',
    'Los Palmitos',
    'Majagual',
    'Morroa',
    'Ovejas',
    'Palmito',
    'Sampués',
    'San Benito Abad',
    'San Juan de Betulia',
    'San Marcos',
    'San Onofre',
    'San Pedro',
    'San Luis de Sincé',
    'Sucre',
    'Santiago de Tolú',
    'Tolú Viejo',
    'Ibagué',
    'Alpujarra',
    'Alvarado',
    'Ambalema',
    'Anzoátegui',
    'Armero',
    'Ataco',
    'Cajamarca',
    'Carmen de Apicala',
    'Casabianca',
    'Chaparral',
    'Coello',
    'Coyaima',
    'Cunday',
    'Dolores',
    'Espinal',
    'Falan',
    'Flandes',
    'Fresno',
    'Guamo',
    'Herveo',
    'Honda',
    'Icononzo',
    'Lérida',
    'Líbano',
    'Mariquita',
    'Melgar',
    'Murillo',
    'Natagaima',
    'Ortega',
    'Palocabildo',
    'Piedras',
    'Planadas',
    'Prado',
    'Purificación',
    'Rio Blanco',
    'Roncesvalles',
    'Rovira',
    'Saldaña',
    'San Antonio',
    'San Luis',
    'Santa Isabel',
    'Suárez',
    'Valle de San Juan',
    'Venadillo',
    'Villahermosa',
    'Villarrica',
    'Cali',
    'Alcalá',
    'Andalucía',
    'Ansermanuevo',
    'Argelia',
    'Bolívar',
    'Buenaventura',
    'Guadalajara de Buga',
    'Bugalagrande',
    'Caicedonia',
    'Calima',
    'Candelaria',
    'Cartago',
    'Dagua',
    'El Águila',
    'El Cairo',
    'El Cerrito',
    'El Dovio',
    'Florida',
    'Ginebra',
    'Guacarí',
    'Jamundí',
    'La Cumbre',
    'La Unión',
    'La Victoria',
    'Obando',
    'Palmira',
    'Pradera',
    'Restrepo',
    'Riofrío',
    'Roldanillo',
    'San Pedro',
    'Sevilla',
    'Toro',
    'Trujillo',
    'Tuluá',
    'Ulloa',
    'Versalles',
    'Vijes',
    'Yotoco',
    'Yumbo',
    'Zarzal',
    'Arauca',
    'Arauquita',
    'Cravo Norte',
    'Fortul',
    'Puerto Rondón',
    'Saravena',
    'Tame',
    'Yopal',
    'Aguazul',
    'Chámeza',
    'Hato Corozal',
    'La Salina',
    'Maní',
    'Monterrey',
    'Nunchía',
    'Orocué',
    'Paz de Ariporo',
    'Pore',
    'Recetor',
    'Sabanalarga',
    'Sácama',
    'San Luis de Gaceno',
    'Támara',
    'Tauramena',
    'Trinidad',
    'Villanueva',
    'Mocoa',
    'Colón',
    'Orito',
    'Puerto Asís',
    'Puerto Caicedo',
    'Puerto Guzmán',
    'Leguízamo',
    'Sibundoy',
    'San Francisco',
    'San Miguel',
    'Santiago',
    'Valle de Guamez',
    'Villagarzón',
    'San Andrés',
    'Providencia',
    'Leticia',
    'El Encanto',
    'La Chorrera',
    'La Pedrera',
    'La Victoria',
    'Miriti Paraná',
    'Puerto Alegría',
    'Puerto Arica',
    'Puerto Nariño',
    'Puerto Santander',
    'Tarapacá',
    'Inírida',
    'Barranco Minas',
    'Mapiripana',
    'San Felipe',
    'Puerto Colombia',
    'La Guadalupe',
    'Cacahual',
    'Pana Pana',
    'Morichal',
    'San José del Guaviare',
    'Calamar',
    'El Retorno',
    'Miraflores',
    'Mitú',
    'Caruru',
    'Pacoa',
    'Taraira',
    'Papunaua',
    'Yavaraté',
    'Puerto Carreño',
    'La Primavera',
    'Santa Rosalía',
    'Cumaribo',
])].sort((a, b) => a.localeCompare(b, 'es'));
