import { Head, useForm } from '@inertiajs/react';
import { useState } from 'react';
import { FiCheckCircle, FiFileText, FiTrash2, FiUploadCloud } from 'react-icons/fi';

export default function ContractingDocuments({ candidate }) {
    const [files, setFiles] = useState([]);
    const form = useForm({ documents: [] });
    const addFiles = (event) => { setFiles((current) => [...current, ...Array.from(event.target.files || [])].slice(0, 5)); event.target.value = ''; };
    const removeFile = (index) => setFiles((current) => current.filter((_, position) => position !== index));
    const submit = (event) => { event.preventDefault(); form.setData('documents', files); form.post(window.location.href, { forceFormData: true, preserveScroll: true, onSuccess: () => { setFiles([]); form.reset(); } }); };
    return <><Head title="Cargar documentos" /><main className="min-h-screen bg-[#090a10] px-4 py-8 text-[#f7f1fb] sm:px-6"><div className="mx-auto max-w-2xl"><div className="mb-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#3c1749] text-[#e2a0f1]"><FiUploadCloud size={25} /></div><p className="mt-6 text-[10px] uppercase tracking-[.28em] text-[#d56bea]">Contratación segura</p><h1 className="mt-3 font-editorial text-4xl text-white">Carga tus documentos</h1><p className="mt-3 text-sm leading-6 text-[#969baa]">Hola, {candidate.name}. Adjunta los archivos solicitados para continuar con tu contratación.</p><p className="mt-1 text-xs text-[#777d8f]">Código de candidato: {candidate.code}</p></div><form onSubmit={submit} className="rounded-2xl border border-[#292d39] bg-[#11131c]/95 p-5 shadow-[0_18px_55px_rgba(0,0,0,.25)] sm:p-7"><div className="rounded-xl border border-[#343044] bg-[#151522] p-4"><p className="text-sm font-medium text-white">Archivos solicitados</p><p className="mt-2 text-xs leading-5 text-[#969baa]">Puedes cargar hasta 5 archivos PDF, JPG o PNG. Cada archivo puede pesar máximo 10 MB.</p></div><label className="mt-6 flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#8c3c9e] bg-[#21132a] px-5 py-10 text-center transition hover:border-[#d56bea] hover:bg-[#2b1735]"><FiUploadCloud className="text-[#d56bea]" size={28} /><span className="mt-3 text-sm font-medium text-white">Seleccionar archivos</span><span className="mt-1 text-xs text-[#a8a0b0]">Puedes seleccionar varios en una sola subida</span><input type="file" className="sr-only" accept=".pdf,.jpg,.jpeg,.png" multiple onChange={addFiles} disabled={files.length >= 5} /></label>{files.length > 0 && <div className="mt-5 space-y-2">{files.map((file, index) => <div key={`${file.name}-${index}`} className="flex items-center gap-3 rounded-lg border border-[#292d39] bg-[#151522] p-3"><FiFileText className="shrink-0 text-[#d56bea]" /><span className="min-w-0 flex-1 truncate text-xs text-white">{file.name}<small className="ml-2 text-[#777d8f]">{(file.size / 1024 / 1024).toFixed(1)} MB</small></span><button type="button" onClick={() => removeFile(index)} className="rounded-md p-2 text-[#ffb1bd] hover:bg-[#321622]" aria-label={`Eliminar ${file.name}`}><FiTrash2 size={15} /></button></div>)}</div>}{form.errors.documents && <p className="mt-3 text-xs text-[#ffb1bd]">{form.errors.documents}</p>}<button type="submit" disabled={!files.length || form.processing} className="velvet-button mt-6 flex w-full items-center justify-center gap-2 py-3 disabled:cursor-not-allowed disabled:opacity-50">{form.processing ? 'Enviando documentos…' : <><FiCheckCircle />Enviar documentos</>}</button><p className="mt-4 text-center text-[11px] leading-5 text-[#777d8f]">El equipo administrativo revisará cada archivo y te contactará si necesita una corrección.</p></form></div></main></>;
}
