import LegalLayout from './LegalLayout';

function Section({ number, title, children }) {
    return <section><h2 className="text-lg font-semibold text-[#e5a1f2]">{number}. {title}</h2><div className="mt-2">{children}</div></section>;
}

export default function PrivacyPolicy() {
    return <LegalLayout eyebrow="Información y confianza" title="Política de privacidad" description="Esta política explica cómo The Velvet Studio recopila, utiliza, conserva y protege la información de las personas que participan en nuestros procesos de aplicación y selección.">
        <Section number="1" title="Responsable del tratamiento"><p>The Velvet Studio es responsable del tratamiento de los datos personales que se recopilan a través de esta plataforma. Para consultas, solicitudes o reclamos relacionados con privacidad puedes escribir a <a className="text-[#e5a1f2] underline" href="mailto:privacidad@thevelvetstudio.co">privacidad@thevelvetstudio.co</a>.</p></Section>
        <Section number="2" title="Información que recopilamos"><p>Podemos recopilar nombre, apellido, sexo, fecha de nacimiento, correo electrónico, WhatsApp, ciudad, experiencia, disponibilidad, modalidad de trabajo, fuente de referencia, motivaciones, portafolio, información de equipo y datos relacionados con el avance de la aplicación.</p><p className="mt-3">Durante la precalificación también podemos solicitar documento de identidad, fotografías, selfie, prueba de vida y resultados de verificación de identidad. Estos datos se solicitan únicamente cuando son necesarios para validar la identidad, la mayoría de edad y la seguridad del proceso.</p></Section>
        <Section number="3" title="Finalidades"><ul className="list-disc space-y-2 pl-5"><li>Recibir, estudiar y dar seguimiento a tu aplicación.</li><li>Contactarte por correo electrónico, WhatsApp u otros canales autorizados.</li><li>Coordinar entrevistas, validaciones y etapas de selección.</li><li>Verificar identidad, mayoría de edad, autenticidad documental y prevenir fraude.</li><li>Administrar perfiles, estados, actividades y comunicaciones dentro de la plataforma.</li><li>Cumplir obligaciones legales, atender solicitudes y proteger los derechos de The Velvet Studio.</li></ul></Section>
        <Section number="4" title="Base de autorización"><p>El tratamiento se realiza con tu autorización previa, expresa e informada, además de las bases legales que resulten aplicables para gestionar la relación precontractual, cumplir obligaciones y proteger la seguridad de la plataforma. La entrega de información es voluntaria; algunos datos son necesarios para estudiar y responder tu aplicación.</p></Section>
        <Section number="5" title="Proveedores y transferencias"><p>Podemos utilizar proveedores tecnológicos que actúan siguiendo nuestras instrucciones, como servicios de correo, almacenamiento, alojamiento y verificación de identidad. Cuando se use un proveedor de verificación, compartiremos únicamente la información necesaria para ejecutar esa validación y recibiremos el resultado correspondiente.</p></Section>
        <Section number="6" title="Conservación y seguridad"><p>Conservamos la información durante el tiempo necesario para las finalidades descritas, atender obligaciones legales y gestionar posibles reclamaciones. Aplicamos controles técnicos y organizativos razonables para evitar acceso no autorizado, pérdida, alteración o divulgación indebida.</p><p className="mt-3">Los documentos de identidad y datos biométricos son información sensible. El acceso se limita al personal autorizado y no deben utilizarse para finalidades distintas a las informadas.</p></Section>
        <Section number="7" title="Tus derechos"><p>Puedes solicitar conocer, actualizar, rectificar o eliminar tus datos, pedir información sobre su uso, retirar tu autorización cuando sea procedente y presentar consultas o reclamos relacionados con el tratamiento. Para hacerlo, escribe a <a className="text-[#e5a1f2] underline" href="mailto:privacidad@thevelvetstudio.co">privacidad@thevelvetstudio.co</a>, indicando tu nombre y la solicitud.</p></Section>
        <Section number="8" title="Cookies"><p>La plataforma utiliza cookies esenciales para mantener la sesión, guardar avances del onboarding y proteger el funcionamiento del sitio. Las cookies no esenciales solo se activarán de acuerdo con tus preferencias cuando estén disponibles.</p></Section>
        <Section number="9" title="Cambios a esta política"><p>Podemos actualizar esta política para reflejar cambios legales, operativos o tecnológicos. Publicaremos la versión vigente en esta URL e indicaremos la fecha de actualización.</p></Section>
        <p className="border-t border-[#292936] pt-6 text-xs text-[#85808d]">Si tienes dudas sobre el alcance legal de esta política, consulta con un profesional especializado en protección de datos. Esta página debe mantenerse actualizada con la razón social, domicilio, canales oficiales y demás información legal de la entidad responsable.</p>
    </LegalLayout>;
}
