import LegalLayout from './LegalLayout';

function Section({ number, title, children }) {
    return <section><h2 className="text-lg font-semibold text-[#e5a1f2]">{number}. {title}</h2><div className="mt-2">{children}</div></section>;
}

export default function TermsAndConditions() {
    return <LegalLayout eyebrow="Reglas del proceso" title="Términos y condiciones" description="Estos términos regulan el uso de la plataforma de aplicación, precalificación y selección de The Velvet Studio.">
        <Section number="1" title="Aceptación"><p>Al acceder a la plataforma, crear una aplicación o completar un formulario de requisitos, declaras que leíste y aceptas estos términos y la <a className="text-[#e5a1f2] underline" href="/politica-de-privacidad" target="_blank" rel="noreferrer">Política de privacidad</a>. Si no estás de acuerdo, no continúes con el proceso.</p></Section>
        <Section number="2" title="Requisitos de participación"><p>La persona que participa debe proporcionar información verdadera, completa y actualizada. Para avanzar a etapas de precalificación o admisión debes cumplir la mayoría de edad y cualquier requisito específico comunicado por The Velvet Studio.</p></Section>
        <Section number="3" title="Aplicación y selección"><p>Enviar una aplicación no garantiza entrevista, contratación, admisión, asignación de oportunidades ni activación de un perfil. The Velvet Studio puede revisar la información, solicitar aclaraciones, realizar validaciones y decidir si la aplicación avanza de etapa.</p><p className="mt-3">Los estados de la plataforma son informativos y pueden cambiar según la revisión del equipo, la documentación recibida y las necesidades operativas.</p></Section>
        <Section number="4" title="Información veraz y verificación"><p>Debes enviar datos propios y documentos legítimos. No puedes utilizar documentos de otra persona, información falsa, archivos manipulados o medios destinados a evadir las verificaciones.</p><p className="mt-3">Cuando el proceso lo requiera, podremos solicitar documento de identidad, selfie, prueba de vida u otras validaciones. Una verificación aprobada no sustituye las revisiones internas ni constituye por sí sola una promesa de contratación.</p></Section>
        <Section number="5" title="Enlaces y comunicaciones"><p>Al proporcionar tu correo o número de WhatsApp autorizas las comunicaciones necesarias para gestionar tu aplicación, incluyendo avisos de estado, entrevistas, formularios y solicitudes de información. Puedes solicitar dejar de recibir comunicaciones no esenciales escribiendo al canal de contacto indicado.</p></Section>
        <Section number="6" title="Uso permitido"><p>La plataforma debe utilizarse de manera legal, respetuosa y exclusivamente para participar en los procesos de The Velvet Studio. Está prohibido intentar acceder a cuentas, tokens, documentos, rutas administrativas o información de otras personas, así como interferir con la seguridad o disponibilidad del servicio.</p></Section>
        <Section number="7" title="Propiedad y contenido"><p>La identidad visual, textos, componentes, marcas y demás elementos de la plataforma pertenecen a The Velvet Studio o se utilizan con autorización. La información que envíes debe ser tuya o contar con los permisos necesarios para compartirla.</p></Section>
        <Section number="8" title="Disponibilidad y cambios"><p>Podemos modificar, suspender o retirar funcionalidades, formularios o etapas del proceso cuando sea necesario. Procuraremos mantener la plataforma disponible, pero no garantizamos que funcione sin interrupciones, errores o cambios de terceros.</p></Section>
        <Section number="9" title="Privacidad y datos personales"><p>El tratamiento de tu información se rige por nuestra <a className="text-[#e5a1f2] underline" href="/politica-de-privacidad" target="_blank" rel="noreferrer">Política de privacidad</a>. Antes de enviar documentos o datos sensibles, asegúrate de leerla y comprender las finalidades y canales de atención.</p></Section>
        <Section number="10" title="Contacto y ley aplicable"><p>Para preguntas sobre estos términos, escribe a <a className="text-[#e5a1f2] underline" href="mailto:info_soporte@thevelvetstudio.co">info_soporte@thevelvetstudio.co</a>. Estos términos deben ser revisados y ajustados con la razón social, domicilio y ley aplicable definidos por The Velvet Studio antes de su publicación definitiva.</p></Section>
        <p className="border-t border-[#292936] pt-6 text-xs text-[#85808d]">Última actualización: 20 de septiembre de 2026. Si modificamos estos términos, publicaremos la nueva versión en esta misma URL.</p>
    </LegalLayout>;
}
