import { Head, Link, router } from '@inertiajs/react';
import { useEffect } from 'react';
import { FiArrowRight, FiEye, FiSearch, FiUsers } from 'react-icons/fi';
import Layout from '../Recruitment/Layout';
import { candidateStatusLabels } from '../../../lib/recruitmentLabels';
import { subscribeToRealtime } from '../../../lib/ably';

export default function Index({ models, filters = {}, trainingMode = false }) {
    useEffect(() => subscribeToRealtime((data, eventName) => {
        if (!trainingMode && ['candidate.updated', 'candidate.status_changed'].includes(eventName)) router.reload({ only: ['models'], preserveScroll: true, preserveState: true });
    }), [trainingMode]);

    return <><Head title={trainingMode ? 'Modelos de prueba' : 'Modelos'} /><Layout><div className="admin-page-content"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[.28em] text-[#d56bea]">Personas</p><h1 className="mt-2 font-editorial text-4xl text-white">{trainingMode ? 'Modelos de prueba' : 'Modelos'}</h1><p className="mt-2 text-sm text-[#969baa]">{trainingMode ? 'Perfiles simulados para practicar durante la inducción.' : 'Consulta los perfiles de las modelos disponibles para la operación.'}</p></div><div className="flex flex-wrap items-center gap-2 text-xs text-[#8e93a5]"><FiUsers />{models.total} modelos{trainingMode && <span className="rounded-full border border-[#b8863b] bg-[#342515] px-2.5 py-1 text-[#ffe1a1]">Sandbox</span>}</div></div><form className="mt-7 flex max-w-xl items-center gap-3" onSubmit={(event) => { event.preventDefault(); const value = event.currentTarget.search.value; router.get('/monitor/models', { search: value, ...(trainingMode ? { sandbox: 1 } : {}) }, { preserveState: true, preserveScroll: true }); }}><div className="relative flex-1"><FiSearch className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#777d8f]" size={15} /><input name="search" defaultValue={filters.search || ''} placeholder="Buscar por nombre o correo" className="velvet-input pl-9" /></div><button type="submit" className="velvet-button">Buscar</button></form><div className="mt-6 grid gap-4 xl:grid-cols-2">{models.data.length ? models.data.map((model) => { const name = `${model.lead.first_name || ''} ${model.lead.last_name || ''}`.trim(); return <article key={model.id} className="rounded-xl border border-[#292d39] bg-[#11131c]/90 p-5 shadow-[0_18px_55px_rgba(0,0,0,.14)]"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#3b2046] text-[#f0c5fa]"><FiUsers /></span><div><h2 className="text-base font-medium text-white">{name}</h2><p className="mt-1 text-xs text-[#858a99]">{model.code} · {model.lead.email}</p></div></div><span className={`rounded-full border px-2.5 py-1 text-[11px] ${trainingMode ? 'border-[#b8863b] bg-[#342515] text-[#ffe1a1]' : 'border-[#9142a7]/50 bg-[#3d164d] text-[#f0c1fa]'}`}>{trainingMode ? 'Perfil de prueba' : candidateStatusLabels[model.status] || model.status}</span></div><Link href={`/monitor/models/${model.id}${trainingMode ? '?sandbox=1' : ''}`} className="mt-5 inline-flex items-center gap-2 text-xs text-[#df8aef] hover:text-white"><FiEye />Ver perfil<FiArrowRight /></Link></article>; }) : <p className="col-span-full rounded-xl border border-dashed border-[#343044] px-5 py-16 text-center text-sm text-[#777d8f]">No hay modelos disponibles.</p>}</div></div></Layout></>;
}
