import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import { FiCalendar, FiCheckCircle, FiClock, FiMail, FiPlus, FiRefreshCw, FiSend } from 'react-icons/fi';
import Layout from '../Layout';
import VelvetDatePicker from '@/Components/VelvetDatePicker';
import VelvetTimePicker from '@/Components/VelvetTimePicker';
import ConfirmationDialog from '@/Components/ConfirmationDialog';

const weekdays = [['1', 'Lun'], ['2', 'Mar'], ['3', 'Mié'], ['4', 'Jue'], ['5', 'Vie'], ['6', 'Sáb'], ['7', 'Dom']];
const dateTime = (value) => new Intl.DateTimeFormat('es-CO', { dateStyle: 'full', timeStyle: 'short', timeZone: 'America/Bogota' }).format(new Date(value));

function Status({ value }) {
    const labels = { AVAILABLE: 'Disponible', BOOKED: 'Reservada', INVITED: 'Invitación enviada', SCHEDULED: 'Agendada', COMPLETED: 'Completada', NO_SHOW: 'No asistió', CANCELLED: 'Cancelada' };
    return <span className={`rounded-full border px-2.5 py-1 text-[11px] ${value === 'AVAILABLE' ? 'border-[#2d8669] bg-[#12372e] text-[#9af2cb]' : value === 'BOOKED' || value === 'SCHEDULED' ? 'border-[#8b46a0] bg-[#321344] text-[#e5a5f2]' : 'border-[#393b4a] text-[#aaa5b5]'}`}>{labels[value] || value}</span>;
}

export default function Index({ slots = [], candidates = [], interviews = [] }) {
    const form = useForm({ from_date: '', to_date: '', weekdays: ['1', '2', '3', '4', '5'], start_time: '09:00', end_time: '17:00' });
    const [pendingReschedule, setPendingReschedule] = useState(null);
    const generate = (event) => { event.preventDefault(); form.post('/admin/interviews/slots', { preserveScroll: true, onSuccess: () => form.reset('from_date', 'to_date') }); };
    const invite = (id) => router.post(`/admin/candidates/${id}/interview-invitation`, {}, { preserveScroll: true });
    const reschedule = () => { if (!pendingReschedule) return; router.post(`/admin/interviews/${pendingReschedule}/reschedule`, {}, { preserveScroll: true, onFinish: () => setPendingReschedule(null) }); };
    const toggleDay = (day) => form.setData('weekdays', form.data.weekdays.includes(day) ? form.data.weekdays.filter((item) => item !== day) : [...form.data.weekdays, day]);
    return <><Head title="Entrevistas" /><Layout><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[.28em] text-[#d56bea]">Agenda</p><h1 className="mt-3 font-editorial text-4xl text-white">Entrevistas</h1><p className="mt-2 text-sm text-[#969baa]">Genera horarios de una hora y envíalos para que cada candidata elija su cita.</p></div><div className="rounded-lg border border-[#343044] bg-[#151522] px-4 py-3 text-xs text-[#aaa5b5]"><FiClock className="mr-2 inline text-[#d56bea]" />Zona horaria: America/Bogota</div></div>
        <section className="mt-8 rounded-xl border border-[#292d39] bg-[#11131c]/90 p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#3c1749] text-[#e2a0f1]"><FiPlus /></span><div><h2 className="text-sm font-medium text-white">Generar franjas disponibles</h2><p className="mt-1 text-xs text-[#7f8495]">Cada franja dura exactamente una hora. No se duplican horarios existentes.</p></div></div><form onSubmit={generate} className="mt-6 grid gap-5 lg:grid-cols-4"><VelvetDatePicker label="Desde" value={form.data.from_date} onChange={(e) => form.setData('from_date', e.target.value)} minDate={new Date()} maxDate={new Date(new Date().setFullYear(new Date().getFullYear() + 1))} error={form.errors.from_date} ariaLabel="Seleccionar fecha inicial" /><VelvetDatePicker label="Hasta" value={form.data.to_date} onChange={(e) => form.setData('to_date', e.target.value)} minDate={new Date()} maxDate={new Date(new Date().setFullYear(new Date().getFullYear() + 1))} error={form.errors.to_date} ariaLabel="Seleccionar fecha final" /><VelvetTimePicker label="Primera hora" value={form.data.start_time} onChange={(e) => form.setData('start_time', e.target.value)} error={form.errors.start_time} /><VelvetTimePicker label="Última hora" value={form.data.end_time} onChange={(e) => form.setData('end_time', e.target.value)} error={form.errors.end_time} /><div className="lg:col-span-3"><p className="text-xs text-[#c8c2ce]">Días de atención</p><div className="mt-2 flex flex-wrap gap-2">{weekdays.map(([value, label]) => <button type="button" key={value} onClick={() => toggleDay(value)} className={`rounded-lg border px-3 py-2 text-xs transition ${form.data.weekdays.includes(value) ? 'border-[#b63bd9] bg-[#4a165c] text-white' : 'border-[#343044] text-[#9993a4] hover:border-[#80508c]'}`}>{label}</button>)}</div></div><div className="flex items-end"><button disabled={form.processing} className="velvet-button w-full gap-2">{form.processing ? 'Generando…' : 'Generar horarios'}<FiPlus /></button></div></form>{form.errors.weekdays && <p className="mt-3 text-xs text-[#ffb1bd]">{form.errors.weekdays}</p>}</section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="rounded-xl border border-[#292d39] bg-[#11131c]/90 p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-medium text-white">Próximas franjas</h2><p className="mt-1 text-xs text-[#7f8495]">Los horarios reservados desaparecen para las demás candidatas.</p></div><FiCalendar className="text-[#d56bea]" /></div><div className="mt-5 max-h-[430px] space-y-2 overflow-y-auto pr-1">{slots.length ? slots.map((slot) => <div key={slot.id} className="flex items-center justify-between gap-3 rounded-lg border border-[#292d39] bg-[#151522] px-4 py-3"><div><p className="text-xs text-[#e8e2ec]">{dateTime(slot.starts_at)}</p><p className="mt-1 text-[11px] text-[#7f8495]">1 hora · hasta {new Intl.DateTimeFormat('es-CO', { timeStyle: 'short', timeZone: 'America/Bogota' }).format(new Date(slot.ends_at))}</p></div><Status value={slot.interview?.status === 'SCHEDULED' ? 'BOOKED' : slot.status} /></div>) : <p className="py-10 text-center text-sm text-[#7f8495]">Todavía no hay franjas generadas.</p>}</div></div><div className="rounded-xl border border-[#292d39] bg-[#11131c]/90 p-6"><div><h2 className="text-sm font-medium text-white">Enviar invitación</h2><p className="mt-1 text-xs text-[#7f8495]">La candidata recibirá los horarios y un enlace personal.</p></div><div className="mt-5 space-y-2">{candidates.length ? candidates.map((candidate) => <div key={candidate.id} className="flex items-center justify-between gap-3 rounded-lg border border-[#292d39] bg-[#151522] px-4 py-3"><div className="min-w-0"><p className="truncate text-xs text-[#eee8f2]">{candidate.lead.first_name} {candidate.lead.last_name}</p><p className="mt-1 text-[11px] text-[#7f8495]">{candidate.code}</p></div><button type="button" onClick={() => invite(candidate.id)} className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-[#854099] px-3 py-2 text-[11px] text-[#e7b2f1] hover:bg-[#351441]"><FiSend />Enviar horarios</button></div>) : <p className="py-10 text-center text-sm text-[#7f8495]">No hay candidatas precalificadas pendientes.</p>}</div></div></section>
        <section className="mt-6 rounded-xl border border-[#292d39] bg-[#11131c]/90 p-6"><div className="flex items-center gap-3"><FiCheckCircle className="text-[#d56bea]" /><div><h2 className="text-sm font-medium text-white">Citas e invitaciones</h2><p className="mt-1 text-xs text-[#7f8495]">Seguimiento de cada entrevista.</p></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead className="border-b border-[#292d39] text-[10px] uppercase tracking-[.16em] text-[#7f8495]"><tr><th className="pb-3">Candidata</th><th className="pb-3">Fecha</th><th className="pb-3">Estado</th><th className="pb-3">Contacto</th><th className="pb-3 text-right">Acción</th></tr></thead><tbody className="divide-y divide-[#292d39]">{interviews.map((interview) => <tr key={interview.id}><td className="py-4 text-[#eee8f2]">{interview.candidate?.lead?.first_name} {interview.candidate?.lead?.last_name}</td><td className="py-4 text-[#b4afbd]">{interview.scheduled_at ? dateTime(interview.scheduled_at) : 'Esperando elección'}</td><td className="py-4"><Status value={interview.status} /></td><td className="py-4 text-[#7f8495]"><FiMail className="mr-1 inline" />{interview.candidate?.lead?.email}</td><td className="py-4 text-right">{interview.status === 'SCHEDULED' && <button type="button" onClick={() => setPendingReschedule(interview.id)} className="inline-flex items-center gap-2 rounded-lg border border-[#80508c] px-3 py-2 text-[11px] text-[#e7b2f1] transition hover:bg-[#351441]"><FiRefreshCw size={13} />Reprogramar</button>}</td></tr>)}</tbody></table>{!interviews.length && <p className="py-8 text-center text-sm text-[#7f8495]">Aún no hay invitaciones.</p>}</div></section>
        <ConfirmationDialog open={Boolean(pendingReschedule)} onOpenChange={(open) => !open && setPendingReschedule(null)} title="Reprogramar entrevista" description="Se liberará la cita actual y se enviarán nuevos horarios a la candidata. Esta acción quedará registrada en el historial." confirmLabel="Reprogramar" onConfirm={reschedule} />
    </Layout></>;
}
